ALTER TABLE ClassS ADD PRIMARY KEY (ID);
ALTER TABLE Guests ADD PRIMARY KEY (ID);
ALTER TABLE Users ADD PRIMARY KEY (ID);
ALTER TABLE GuestStatus ADD PRIMARY KEY (ID);
ALTER TABLE Locations ADD PRIMARY KEY (ID);
ALTER TABLE Roles ADD PRIMARY KEY (ID);
ALTER TABLE BasementRats ADD PRIMARY KEY (ID);

/*Dependet tables*/
ALTER TABLE Tavern ADD PRIMARY KEY (ID);
ALTER TABLE Tavern ADD FOREIGN KEY (OwnerID) REFERENCES Users (ID);
ALTER TABLE Tavern ADD FOREIGN KEY (LocationID) REFERENCES Locations (ID);

ALTER TABLE BasementRats ADD PRIMARY KEY (ID);
ALTER TABLE BasementRats ADD FOREIGN KEY (tavern_ID) REFERENCES Tavern (ID);

ALTER TABLE SuppliesAndServices ADD PRIMARY KEY (ID);
ALTER TABLE SuppliesAndServices ADD FOREIGN KEY (tavern_ID) REFERENCES Tavern (ID);

ALTER TABLE Sales ADD PRIMARY KEY (ID);
ALTER TABLE Sales ADD FOREIGN KEY (SupplyOrService_ID) REFERENCES SuppliesAndServices (ID);

ALTER TABLE Status ADD PRIMARY KEY (ID);
ALTER TABLE Status ADD FOREIGN KEY (tavern_ID) REFERENCES Tavern (ID);

ALTER TABLE SupplyDelivery ADD PRIMARY KEY (ID);
ALTER TABLE SupplyDelivery ADD FOREIGN KEY (SupplyOrService_ID) REFERENCES SuppliesAndServices (ID);

ALTER TABLE Level ADD FOREIGN KEY (class_ID) REFERENCES Class (ID);
ALTER TABLE Level ADD FOREIGN KEY (guests_ID) REFERENCES Guests (ID);
